Add missing include for mtcr_cables.h when CABLES_SUPPORT is enabled and forward declaration for read_device_id to fix compilation errors with -Werror=implicit-function-declaration.
Changes:

Add #include "mtcr_ul/mtcr_cables.h" when CABLES_SUPPORT is defined to declare get_cable_id() function

Add forward declaration for read_device_id() at the top of the file to ensure it's visible when called

Fixes compilation errors:

tools_dev_types.c:604:16: error: implicit declaration of function 'get_cable_id' tools_dev_types.c:640:16: error: implicit declaration of function 'read_device_id'