mlxdpa: Fix missing include in elf_types.hpp
To fix compiler error with g++ (GCC) 13.2.0

    ./elfio/elf_types.hpp:30:20: error: 'uint16_t' does not name a type