mstflint | mtcr.py can't be used on Python2 systems
Description: fixed python3 string formatting which broke mtrc for python2
before:
>>> import mtcr.py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mtcr.py", line 77
    print(f"Error loading CMTCR: {e}")
                                    ^
SyntaxError: invalid syntax
>>>

after:
>>> import mtcr
>>>