fix implicit declaration of function 'get_cable_id'
Add missing include for mtcr_cables.h when CABLES_SUPPORT is enabled.
The function get_cable_id() is declared in mtcr_ul/mtcr_cables.h but
this header was not included in tools_dev_types.c, causing compilation
errors with -Werror=implicit-function-declaration.

Fixes compilation error:
  tools_dev_types.c:604:16: error: implicit declaration of function 'get_cable_id'