compilation error |  missing stdexcept include + 'for' loop initial declarations are only allowed in C99 mode
Description: compiling without -std=c99 or -std=gnu99 we get this error: 'for' loop initial declarations are only allowed in C99 mode
after fix - a missing include was needed for stdexcept. added.
now compiles successfully in both formats:
./configure --disable-openssl
./configure --enable-cables