mlxdpa: elfio: Include <cstdint> when necessary to have definition for "[u]?int[0-9]+_t"-family of types.
This commit addresses compilation failure below, which is caused
by changes in standard headers on modern versions of GCC:

    In file included from elfio/elfio.hpp:34,
                     from cryptodata.cpp:15:
    ./elfio/elf_types.hpp:30:20: error: 'uint16_t' does not name a type
       30 | using Elf_Half   = uint16_t;
          |                    ^~~~~~~~
    ./elfio/elf_types.hpp:1:1: note: 'uint16_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
      +++ |+#include <cstdint>
        1 | /*

See https://gcc.gnu.org/gcc-13/porting_to.html for reference.

(cherry picked from commit bc33aa09e2e1340f9d4cfba1a915b0fe25b17eb4)
Signed-off-by: AlexBlago <alexbl@nvidia.com>