dev_mgt: include missing function declaration
The dev_mgt fails to build with the following error:

tools_dev_types.c: In function 'dm_get_device_id_inner':
tools_dev_types.c:695:13: error: implicit declaration of function 'read_device_id'; did you mean 'dm_get_device_id'? [-Wimplicit-function-declaration]
  695 |         if (read_device_id(mf, &dword) != 4) {
      |             ^~~~~~~~~~~~~~
      |             dm_get_device_id

This commit includes mtcr_ul_com.h (where read_device_id
is defined) into tools_dev_types.c to fix the error.

Signed-off-by: Til Kaiser <mail@tk154.de>